name: Django Company API Test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python 3.8 and pipenv
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev --system

    - name: Set environment variables
      env:
        PYTHONPATH: ${{ github.workspace }}/api/whoishiring
        DJANGO_SETTINGS_MODULE: whoishiring.settings

    - name: Run tests
      working-directory: ./api/whoishiring
      run: pytest -vv