name: Django Company API Test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.8 and pipenv
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set environment variables
      env:
        SECRET_KEY: ${{ secrets.DJANGO_SETTINGS_MODULE }}
      run: |
        echo "::set-env name=PYTHONPATH=:api/whoishiring"
        echo 'export DJANGO_SETTINGS_MODULE=whoishiring.settings' 

    - name: Run tests
      run: |
        pip install pytest
        python pytest test_api.py -s -v --durations=0
