name: Django API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11.0 and create virtual environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.0"

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          pip install -U pip setuptools wheel
          pip install flake8
          pip install -r requirements.txt

      - name: Set up Django environment variable
        run: echo "DJANGO_SETTINGS_MODULE=whoishiring.settings" >> $GITHUB_ENV

      - name: Test with pytest
        run: |
          python -m pytest --collect-only
          python -m flake8 .