name: Django Company API Test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.8 and pipenv
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set environment variables
      run: |
        echo 'export PYTHONPATH=$PYTHONPATH:$PYTHONPATH/api/whoishiring' >> $GITHUB_ENV
        echo 'export DJANGO_SETTINGS_MODULE=whoishiring.settings' >> $GITHUB_ENV

    - name: Run tests
      working-directory: ./api/whoishiring
      run: pytest -vv
