name: Django API Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11.0
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.0"

      - name: Install dependencies
        run: |
          pip install flake8
          pip install -r requirements.txt
          export PYTHONPATH=$PYTHONPATH:$PWD/api/whoishiring
          export DJANGO_SETTINGS_MODULE="whoishiring.settings"
      - name: Test with pytest
        run: |
          pytest api/whoishiring -s -v --durations=0
          flake8 .