name: Django Company API tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8.5 and pipenv
        uses: actions/setup-python@v2
        with:
          python-version: "3.8.5"
        run: |
          pip install pipenv --upgrade

      - name: Install dependencies
        run: |
          pipenv install --system
          pip install pytest pytest-cov

      - name: Set environment variables
        env:
          PYTHONPATH: ${{ github.workspace }}/api/whoishiring
          DJANGO_SETTINGS_MODULE: whoishiring.settings
        run: |
          echo "PYTHONPATH=$PYTHONPATH" >> $GITHUB_ENV
          echo "DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE" >> $GITHUB_ENV

      - name: Run tests
        run: |
          pytest api/coronavstech -s -v --durations=0 --cov=. -m "not skip_in_ci"
