name: Django API Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}/api/whoishiring
      DJANGO_SETTINGS_MODULE: whoishiring.settings
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11.0
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.0"

      - name: Install dependencies
        run: |
          pip install flake8
          pip install -r requirements.txt

      - name: Test with pytest
        run: |
          pytest --collect-only
          flake8 .